// <auto-generated />
using System;
using Labilletterie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labilletterie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Labilletterie.Models.Billet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcheteurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeQR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvenementId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixPaye")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StatutScan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeBillet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcheteurId");

                    b.HasIndex("EvenementId");

                    b.ToTable("Billets");
                });

            modelBuilder.Entity("Labilletterie.Models.Evenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPrive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePassePrive")
                        .HasColumnType("TEXT");

                    b.Property<int>("NombrePlacesRestantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePlacesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganisateurId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganisateurId");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("Labilletterie.Models.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BilletId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateScan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanneParId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BilletId");

                    b.HasIndex("ScanneParId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("Labilletterie.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsFidelite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Labilletterie.Models.Billet", b =>
                {
                    b.HasOne("Labilletterie.Models.Utilisateur", "Acheteur")
                        .WithMany()
                        .HasForeignKey("AcheteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labilletterie.Models.Evenement", "Evenement")
                        .WithMany("Billets")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acheteur");

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("Labilletterie.Models.Evenement", b =>
                {
                    b.HasOne("Labilletterie.Models.Utilisateur", "Organisateur")
                        .WithMany()
                        .HasForeignKey("OrganisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisateur");
                });

            modelBuilder.Entity("Labilletterie.Models.Scan", b =>
                {
                    b.HasOne("Labilletterie.Models.Billet", "Billet")
                        .WithMany()
                        .HasForeignKey("BilletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labilletterie.Models.Utilisateur", "ScannePar")
                        .WithMany()
                        .HasForeignKey("ScanneParId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billet");

                    b.Navigation("ScannePar");
                });

            modelBuilder.Entity("Labilletterie.Models.Evenement", b =>
                {
                    b.Navigation("Billets");
                });
#pragma warning restore 612, 618
        }
    }
}
